version: '3'
#==========================VOLUMES==========================
volumes:
  portainer_data:
  mkdocs_data:

#==========================SERVICES==========================
services:
#---------------------------SIG-LEGACY---------------------- 
  sigfap:
    build: 
      context: ./sigfap-php
      args:
        uid: ${UID}
    container_name: sig-legacy
    ports:
      - 80:80
    volumes:
      - ./sigfap-php/sigfap:/var/www/html
    restart: always

#----------------------------PGSQL--------------------------
  db:
    image: postgres:10.11
    container_name: legacy-db
    restart: always
    volumes:
      - ./pgsql:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}